[project]
name = "backend"
version = "0.1.0"
description = "Backend for Budgeto: seamlessly track your budget and expenses."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
